## Simulation
- using the entire code

In [ ]:
# imports
import numpy as np
import gymnasium as gym
from gymnasium import spaces
import random
# setting up the environment
env = gym.make("FrozenLake-v1", is_slippery=False, render_mode="human")
action_size = env.action_space.n
state_size = env.observation_space.n
# the Q-table
qtable = np.zeros((state_size, action_size))
print("Q-table:\n")
print(qtable)
# hyperparameters
total_episodes =2000          # Total episodes
max_steps = 25               # Max steps per episode
learning_rate = 0.2           # Learning rate
gamma = 0.99                  # Discounting rate
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.05            # Minimum exploration probability
decay_rate = 0.005
# training
rewards = []

# Training loop
for episode in range(total_episodes):
    state, info = env.reset()
    done = False
    total_rewards = 0

    for step in range(max_steps):
        # Epsilon-greedy action selection
        if random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()  # Explore
        else:
            action = np.argmax(qtable[state, :])  # Exploit

        # Take action
        new_state, reward, done, truncated, info = env.step(action)

        # Update Q-table
        qtable[state, action] = qtable[state, action] + learning_rate * (
            reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action]
        )

        total_rewards += reward
        state = new_state

        if done or truncated:
            break

    # Update epsilon
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)
    rewards.append(total_rewards)

# Print training results
print("Training completed.")
print("Score over time (success rate):", sum(rewards) / total_episodes)
print("Q-table:")
print(qtable)

# Evaluation loop with debugging
eval_max_steps = 100
for episode in range(5):
    state, info = env.reset()
    done = False
    print("****************************************************")
    print("EPISODE", episode + 1)

    for step in range(eval_max_steps):
        action = np.argmax(qtable[state, :])
        new_state, reward, done, truncated, info = env.step(action)
        print(f"Step {step}: State {state}, Action {action}, New State {new_state}, Reward {reward}")

        if done or truncated:
            env.render()
            print("Number of steps:", step + 1)
            print("Reward:", reward)
            break
        state = new_state
    else:
        print("Episode did not terminate within", eval_max_steps, "steps.")
        print("Final state:", state)

env.close()

Q-table:

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
